export const data = [
  {
    agent: null,
    allowed_actions: [
      {
        code: '001',
        description: 'Pending',
      },
      {
        code: 'CANC_RA',
        description: 'Cancel',
      },
      {
        code: 'NOSHOW_RA',
        description: 'No show',
      },
    ],
    arrival: {
      code: '001',
      description: 'Not sure yet',
    },
    booked_on: {
      date: '2025-11-27',
      hour: 12,
      minute: 2,
    },
    booking_nbr: '85515786502',
    bypassed_ota_revisions: null,
    channel_booking_nbr: null,
    company_name: null,
    company_tax_nbr: null,
    cost: null,
    currency: {
      code: 'USD',
      id: 4,
      symbol: 'US$',
    },
    events: [
      {
        date: '2025-11-27',
        hour: 12,
        id: null,
        minute: 2,
        second: 21,
        type: 'Conf. email',
        user: 'System',
      },
      {
        date: '2025-11-27',
        hour: 12,
        id: 8789316,
        minute: 2,
        second: 15,
        type: 'Confirmed',
        user: 'ron',
      },
    ],
    extra_services: null,
    extras: [
      {
        key: 'is_backend',
        value: 'true',
      },
    ],
    financial: {
      cancelation_penality_as_if_today: 0.0,
      collected: 0.0,
      due_amount: 155.4,
      due_dates: null,
      gross_cost: 0.0,
      gross_total: 155.4,
      invoice_nbr: '855157',
      payments: null,
      refunds: 0.0,
      total_amount: 140.0,
    },
    format: {
      from_date: 'Mon, 08 Dec 2025',
      to_date: 'Tue, 09 Dec 2025',
    },
    from_date: '2025-12-08',
    guest: {
      address: '',
      alternative_email: null,
      cci: null,
      city: null,
      country: {
        cities: null,
        code: 'CY',
        currency: null,
        flag: null,
        gmt_offset: 0,
        id: 6,
        market_places: null,
        name: 'Cyprus',
        phone_prefix: null,
      },
      country_id: 6,
      country_phone_prefix: '+357',
      dob: null,
      email: 'ronaldsayeg.h@gmail.com',
      first_name: 'Ronald',
      id: 721179,
      id_info: null,
      is_main: false,
      last_name: 'Sayegh',
      mobile: '03236623',
      mobile_without_prefix: '03236623',
      nbr_confirmed_bookings: 3,
      notes: '',
      password: null,
      subscribe_to_news_letter: false,
    },
    is_direct: true,
    is_editable: true,
    is_in_loyalty_mode: false,
    is_pms_enabled: true,
    is_requested_to_cancel: null,
    occupancy: {
      adult_nbr: 1,
      children_nbr: 0,
      infant_nbr: 0,
    },
    origin: {
      Icon: 'https://x.igloorooms.com/assets/images/png/direct.png',
      Label: 'Direct | manual',
    },
    ota_commission: null,
    ota_guarante: null,
    ota_guarantee_plain: null,
    ota_manipulations: null,
    ota_notes: null,
    ota_services: null,
    ota_services_plain: null,
    payment_collect: null,
    payment_type: null,
    pickup_info: null,
    promo_key: '',
    property: {
      address: null,
      adult_child_constraints: null,
      affiliates: null,
      agents: null,
      allowed_booking_sources: null,
      allowed_cards: null,
      allowed_payment_methods: null,
      amenities: null,
      aname: null,
      area: null,
      baby_cot_offering: null,
      be_listing_mode: null,
      calendar_extra: null,
      calendar_legends: null,
      city: null,
      cleaning_frequency: null,
      company: null,
      contacts: null,
      country: null,
      currency: null,
      description: null,
      extra_info: null,
      id: 42,
      images: null,
      internet_offering: null,
      is_automatic_check_in_out: null,
      is_be_enabled: null,
      is_frontdesk_enabled: null,
      is_multi_property: null,
      is_pms_enabled: null,
      is_vacation_rental: null,
      location: null,
      max_nights: 0,
      mpo: null,
      name: 'igloorooms Demo Hotel',
      parking_offering: null,
      payment_methods: null,
      perma_link: null,
      pets_acceptance: null,
      phone: null,
      pickup_service: null,
      postal: null,
      privacy_policy: null,
      promotions: null,
      registered_name: null,
      roomtypes: null,
      social_media: null,
      sources: null,
      space_theme: null,
      tags: null,
      tax_nbr: null,
      tax_statement: null,
      taxation_strategy: null,
      taxes: null,
      time_constraints: null,
    },
    remark: '',
    rooms: [
      {
        applicable_policies: [
          {
            brackets: [
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '000',
                currency_id: 4,
                due_on: '2025-11-27',
                due_on_formatted: 'Thursday, 27 Nov 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: 'Do not use',
              },
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '000',
                currency_id: 4,
                due_on: '2025-12-07',
                due_on_formatted: 'Sunday, 7 Dec 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: 'Do not use',
              },
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '007',
                currency_id: 4,
                due_on: '2025-12-08',
                due_on_formatted: 'Monday, 8 Dec 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: '0%',
              },
            ],
            combined_statement: 'No penalty if cancelled before Sunday, 7 Dec 2025, 14:00.',
            type: 'cancelation',
          },
          {
            brackets: [
              {
                amount: 35.0,
                amount_formatted: 'US$35.00',
                code: '001',
                currency_id: 4,
                due_on: '2025-11-27',
                due_on_formatted: null,
                gross_amount: 38.85,
                gross_amount_formatted: 'US$38.85',
                statement: '25% of your booking total will be charged',
              },
            ],
            combined_statement: '25% of your booking total will be charged',
            type: 'guarantee',
          },
        ],
        assigned_units_pool: 'fde6b2a1-d689-44bb-8367-253e4aecf6b8',
        bed_preference: null,
        calendar_extra: '',
        check_in: false,
        cost: null,
        days: [
          {
            amount: 140.0,
            cost: null,
            date: '2025-12-08',
          },
        ],
        departure_time: {
          code: '',
          description: '',
        },
        from_date: '2025-12-08',
        gross_cost: null,
        gross_guarantee: 38.85,
        gross_total: 155.4,
        guarantee: 35.0,
        guest: {
          address: null,
          alternative_email: null,
          cci: null,
          city: null,
          country: null,
          country_id: null,
          country_phone_prefix: null,
          dob: null,
          email: null,
          first_name: 'r',
          id: null,
          id_info: null,
          is_main: false,
          last_name: 'Sayegh',
          mobile: null,
          mobile_without_prefix: null,
          nbr_confirmed_bookings: 0,
          notes: null,
          password: null,
          subscribe_to_news_letter: null,
        },
        identifier: '2640369f-354f-461e-ade5-b738e8b94625',
        in_out: {
          code: '000',
          description: 'Not Set',
        },
        is_split: null,
        notes: '',
        occupancy: {
          adult_nbr: 1,
          children_nbr: 0,
          infant_nbr: null,
        },
        ota_meta: null,
        ota_meta_plain: null,
        ota_taxes: null,
        ota_unique_id: null,
        parent_room_identifier: null,
        prepayment_amount: null,
        prepayment_amount_gross: null,
        rateplan: {
          agents: null,
          assignable_units: null,
          cancelation: 'No penalty if cancelled before Sunday, 7 Dec 2025, 14:00.',
          custom_text: null,
          extra_bed_for_code: null,
          extra_bed_max: null,
          extra_bed_rate_per_night: null,
          extra_bed_rate_per_night_additional_child: null,
          extra_bed_rate_per_night_first_child: null,
          guarantee: '25% of your booking total will be charged',
          id: 3755,
          is_active: null,
          is_available_to_book: false,
          is_booking_engine_enabled: null,
          is_channel_enabled: null,
          is_closed: null,
          is_derived: false,
          is_extra_bed_free_for_children: false,
          is_non_refundable: false,
          is_targeting_travel_agency: null,
          meal_plan: {
            code: '003',
            name: null,
          },
          name: 'Breakfast & dinner/Half-board',
          not_available_reason: null,
          pre_payment_amount: null,
          pre_payment_amount_gross: null,
          rate_restrictions: null,
          selected_variation: {
            IS_MLS_VIOLATED: false,
            MLS_ALERT: null,
            MLS_ALERT_VALUE: null,
            adult_child_offering: '1 adult',
            adult_nbr: 1,
            amount: null,
            amount_gross: null,
            amount_per_night: null,
            amount_per_night_gross: null,
            applicable_policies: null,
            bed_preference_code: null,
            child_nbr: 0,
            discount_pct: null,
            discounted_amount: null,
            discounted_gross_amount: null,
            extra_bed_free_nbr: null,
            extra_bed_nbr: null,
            extra_bed_rate_per_night: null,
            food_nbr_upsell: 0,
            infant_nbr: null,
            is_lmd: null,
            nights: null,
            nights_nbr: null,
            prepayment_amount: null,
            prepayment_amount_gross: null,
            rate_plan_id: 3755,
            smoking_code: null,
            total_before_discount: null,
          },
          sell_mode: null,
          short_name: 'Half board',
          sleeps: null,
          variations: null,
        },
        roomtype: {
          amenities: null,
          availabilities: null,
          bedding_setup: null,
          description: null,
          exposed_inventory: null,
          id: 111,
          images: null,
          inventory: null,
          is_active: null,
          is_available_to_book: null,
          is_bed_configuration_enabled: null,
          is_channel_enabled: null,
          main_image: null,
          name: 'Premium Suites',
          not_available_reason: null,
          occupancy_default: null,
          occupancy_max: null,
          physicalrooms: null,
          rate: null,
          rateplans: null,
          size: null,
          smoking_option: null,
        },
        sharing_persons: [
          {
            address: null,
            alternative_email: null,
            cci: null,
            city: null,
            country: {
              cities: null,
              code: null,
              currency: null,
              flag: null,
              gmt_offset: 0,
              id: null,
              market_places: null,
              name: null,
              phone_prefix: null,
            },
            country_id: null,
            country_phone_prefix: null,
            dob: '1900-01-01',
            email: null,
            first_name: 'r',
            id: 131717,
            id_info: {
              number: '',
              type: {
                code: '001',
                description: 'Passport',
              },
            },
            is_main: true,
            last_name: 'Sayegh',
            mobile: null,
            mobile_without_prefix: null,
            nbr_confirmed_bookings: 0,
            notes: null,
            password: null,
            subscribe_to_news_letter: null,
          },
        ],
        smoking_option: null,
        taxes: null,
        to_date: '2025-12-09',
        total: 140.0,
        unit: {
          calendar_cell: null,
          hk_status: null,
          housekeeper: null,
          id: 3,
          is_active: null,
          name: '102',
        },
      },
    ],
    source: {
      code: '003',
      description: 'Phone/Email',
      id: null,
      tag: '',
      type: null,
    },
    status: {
      code: '002',
      description: 'Confirmed',
    },
    system_id: 14952882,
    to_date: '2025-12-09',
    total: 140.0,
  },
  {
    agent: null,
    allowed_actions: [
      {
        code: '001',
        description: 'Pending',
      },
      {
        code: 'CANC_RA',
        description: 'Cancel',
      },
      {
        code: 'NOSHOW_RA',
        description: 'No show',
      },
    ],
    arrival: {
      code: '001',
      description: 'Not sure yet',
    },
    booked_on: {
      date: '2025-11-25',
      hour: 18,
      minute: 59,
    },
    booking_nbr: '52345317700',
    bypassed_ota_revisions: null,
    channel_booking_nbr: null,
    company_name: null,
    company_tax_nbr: null,
    cost: null,
    currency: {
      code: 'USD',
      id: 4,
      symbol: 'US$',
    },
    events: [
      {
        date: '2025-11-27',
        hour: 14,
        id: 8789471,
        minute: 38,
        second: 43,
        type: 'Confirmed',
        user: 'A35',
      },
      {
        date: '2025-11-27',
        hour: 14,
        id: null,
        minute: 38,
        second: 31,
        type: 'Canc. email',
        user: 'System',
      },
      {
        date: '2025-11-27',
        hour: 14,
        id: 8789469,
        minute: 38,
        second: 28,
        type: 'Cancelled',
        user: 'A35',
      },
      {
        date: '2025-11-26',
        hour: 12,
        id: 8788681,
        minute: 35,
        second: 42,
        type: 'Confirmed',
        user: 'A35',
      },
      {
        date: '2025-11-26',
        hour: 12,
        id: 8788679,
        minute: 35,
        second: 34,
        type: 'Cancelled',
        user: 'A35',
      },
      {
        date: '2025-11-26',
        hour: 12,
        id: 8788677,
        minute: 35,
        second: 27,
        type: 'Pending',
        user: 'A35',
      },
      {
        date: '2025-11-25',
        hour: 18,
        id: null,
        minute: 59,
        second: 25,
        type: 'Conf. email',
        user: 'System',
      },
      {
        date: '2025-11-25',
        hour: 18,
        id: 8788067,
        minute: 59,
        second: 18,
        type: 'Confirmed',
        user: 'A35',
      },
    ],
    extra_services: null,
    extras: [
      {
        key: 'private_note',
        value: 'My private note',
      },
      {
        key: 'is_backend',
        value: 'true',
      },
    ],
    financial: {
      cancelation_penality_as_if_today: 100.0,
      collected: 279.72,
      due_amount: 100.0,
      due_dates: null,
      gross_cost: 0.0,
      gross_total: 379.72,
      invoice_nbr: '523453',
      payments: [
        {
          amount: 20.0,
          book_nbr: '52345317700',
          currency: {
            code: 'USD',
            id: 4,
            symbol: 'US$',
          },
          date: '2025-11-26',
          designation: 'Payment',
          id: 16724,
          is_receipt_issued: true,
          payment_gateway_code: null,
          payment_method: {
            code: '001',
            description: 'Cash',
          },
          payment_type: {
            code: '001',
            description: 'Payment',
            operation: 'CR',
          },
          receipt_nbr: 'RC-14',
          reference: '',
          time_stamp: {
            day: '2025-11-26',
            hour: 10,
            minute: 10,
            second: 1,
            user: 'ron',
          },
        },
        {
          amount: 259.72,
          book_nbr: '52345317700',
          currency: {
            code: 'USD',
            id: 4,
            symbol: 'US$',
          },
          date: '2025-11-26',
          designation: 'Cash',
          id: 16739,
          is_receipt_issued: null,
          payment_gateway_code: null,
          payment_method: {
            code: '001',
            description: 'Cash',
          },
          payment_type: {
            code: '001',
            description: 'Payment',
            operation: 'CR',
          },
          receipt_nbr: null,
          reference: '',
          time_stamp: {
            day: '2025-11-26',
            hour: 11,
            minute: 52,
            second: 52,
            user: 'ron',
          },
        },
      ],
      refunds: 0.0,
      total_amount: 252.0,
    },
    format: {
      from_date: 'Tue, 25 Nov 2025',
      to_date: 'Thu, 27 Nov 2025',
    },
    from_date: '2025-11-25',
    guest: {
      address: '',
      alternative_email: null,
      cci: null,
      city: null,
      country: {
        cities: null,
        code: 'BZ',
        currency: null,
        flag: null,
        gmt_offset: 0,
        id: 486,
        market_places: null,
        name: 'Belize',
        phone_prefix: null,
      },
      country_id: 486,
      country_phone_prefix: '+501',
      dob: null,
      email: 'estest.test@gmail.com',
      first_name: 'Fa',
      id: 528363,
      id_info: null,
      is_main: false,
      last_name: 'aL',
      mobile: '12345678',
      mobile_without_prefix: '12345678',
      nbr_confirmed_bookings: 50,
      notes: '',
      password: null,
      subscribe_to_news_letter: false,
    },
    is_direct: true,
    is_editable: true,
    is_in_loyalty_mode: false,
    is_pms_enabled: true,
    is_requested_to_cancel: false,
    occupancy: {
      adult_nbr: 2,
      children_nbr: 0,
      infant_nbr: 0,
    },
    origin: {
      Icon: 'https://x.igloorooms.com/assets/images/png/direct.png',
      Label: 'Direct | manual',
    },
    ota_commission: null,
    ota_guarante: null,
    ota_guarantee_plain: null,
    ota_manipulations: null,
    ota_notes: null,
    ota_services: null,
    ota_services_plain: null,
    payment_collect: null,
    payment_type: null,
    pickup_info: {
      currency: {
        code: 'USD',
        id: 4,
        symbol: 'US$',
      },
      date: '2025-11-26',
      details: 'ftff',
      hour: 12,
      minute: 22,
      nbr_of_units: 1,
      selected_option: {
        amount: 50.0,
        currency: {
          code: 'USD',
          id: 4,
          symbol: 'US$',
        },
        id: 19,
        location: {
          description: 'Beirut International Airport',
          id: 1,
        },
        pricing_model: {
          code: '002',
          description: 'Person',
        },
        vehicle: {
          capacity: 4,
          code: '002',
          description: 'Sedan car (2 large & 3 small suitcases)',
        },
      },
      total: 100.0,
    },
    promo_key: '',
    property: {
      address: null,
      adult_child_constraints: null,
      affiliates: null,
      agents: null,
      allowed_booking_sources: null,
      allowed_cards: null,
      allowed_payment_methods: null,
      amenities: null,
      aname: null,
      area: null,
      baby_cot_offering: null,
      be_listing_mode: null,
      calendar_extra: null,
      calendar_legends: null,
      city: null,
      cleaning_frequency: null,
      company: null,
      contacts: null,
      country: null,
      currency: null,
      description: null,
      extra_info: null,
      id: 42,
      images: null,
      internet_offering: null,
      is_automatic_check_in_out: null,
      is_be_enabled: null,
      is_frontdesk_enabled: null,
      is_multi_property: null,
      is_pms_enabled: null,
      is_vacation_rental: null,
      location: null,
      max_nights: 0,
      mpo: null,
      name: 'igloorooms Demo Hotel',
      parking_offering: null,
      payment_methods: null,
      perma_link: null,
      pets_acceptance: null,
      phone: null,
      pickup_service: null,
      postal: null,
      privacy_policy: null,
      promotions: null,
      registered_name: null,
      roomtypes: null,
      social_media: null,
      sources: null,
      space_theme: null,
      tags: null,
      tax_nbr: null,
      tax_statement: null,
      taxation_strategy: null,
      taxes: null,
      time_constraints: null,
    },
    remark: '',
    rooms: [
      {
        applicable_policies: [
          {
            brackets: [
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '007',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: 'Tuesday, 25 Nov 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: '0%',
              },
            ],
            combined_statement: '',
            type: 'cancelation',
          },
          {
            brackets: [
              {
                amount: 31.5,
                amount_formatted: 'US$31.50',
                code: '001',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: null,
                gross_amount: 34.965,
                gross_amount_formatted: 'US$34.97',
                statement: '25% of your booking total will be charged',
              },
            ],
            combined_statement: '25% of your booking total will be charged',
            type: 'guarantee',
          },
        ],
        assigned_units_pool: null,
        bed_preference: null,
        calendar_extra: '',
        check_in: false,
        cost: null,
        days: [
          {
            amount: 126.0,
            cost: null,
            date: '2025-11-25',
          },
        ],
        departure_time: {
          code: '',
          description: '',
        },
        from_date: '2025-11-25',
        gross_cost: null,
        gross_guarantee: 34.965,
        gross_total: 139.86,
        guarantee: 31.5,
        guest: {
          address: null,
          alternative_email: null,
          cci: null,
          city: null,
          country: null,
          country_id: null,
          country_phone_prefix: null,
          dob: null,
          email: null,
          first_name: 'test',
          id: null,
          id_info: null,
          is_main: false,
          last_name: 'test',
          mobile: null,
          mobile_without_prefix: null,
          nbr_confirmed_bookings: 0,
          notes: null,
          password: null,
          subscribe_to_news_letter: null,
        },
        identifier: 'ed68af2f-04e9-4e7b-9e54-ae9a2d059fb7',
        in_out: {
          code: '000',
          description: 'Not Set',
        },
        is_split: null,
        notes: '',
        occupancy: {
          adult_nbr: 2,
          children_nbr: 0,
          infant_nbr: null,
        },
        ota_meta: null,
        ota_meta_plain: null,
        ota_taxes: null,
        ota_unique_id: null,
        parent_room_identifier: null,
        prepayment_amount: null,
        prepayment_amount_gross: null,
        rateplan: {
          agents: null,
          assignable_units: null,
          cancelation: '',
          custom_text: null,
          extra_bed_for_code: null,
          extra_bed_max: null,
          extra_bed_rate_per_night: null,
          extra_bed_rate_per_night_additional_child: null,
          extra_bed_rate_per_night_first_child: null,
          guarantee: '25% of your booking total will be charged',
          id: 3755,
          is_active: null,
          is_available_to_book: false,
          is_booking_engine_enabled: null,
          is_channel_enabled: null,
          is_closed: null,
          is_derived: false,
          is_extra_bed_free_for_children: false,
          is_non_refundable: false,
          is_targeting_travel_agency: null,
          meal_plan: {
            code: '003',
            name: null,
          },
          name: 'Breakfast & dinner/Half-board',
          not_available_reason: null,
          pre_payment_amount: null,
          pre_payment_amount_gross: null,
          rate_restrictions: null,
          selected_variation: {
            IS_MLS_VIOLATED: false,
            MLS_ALERT: null,
            MLS_ALERT_VALUE: null,
            adult_child_offering: '2 adults',
            adult_nbr: 2,
            amount: null,
            amount_gross: null,
            amount_per_night: null,
            amount_per_night_gross: null,
            applicable_policies: null,
            bed_preference_code: null,
            child_nbr: 0,
            discount_pct: null,
            discounted_amount: null,
            discounted_gross_amount: null,
            extra_bed_free_nbr: null,
            extra_bed_nbr: null,
            extra_bed_rate_per_night: null,
            food_nbr_upsell: 0,
            infant_nbr: null,
            is_lmd: null,
            nights: null,
            nights_nbr: null,
            prepayment_amount: null,
            prepayment_amount_gross: null,
            rate_plan_id: 3755,
            smoking_code: null,
            total_before_discount: null,
          },
          sell_mode: null,
          short_name: 'Half board',
          sleeps: null,
          variations: null,
        },
        roomtype: {
          amenities: null,
          availabilities: null,
          bedding_setup: null,
          description: null,
          exposed_inventory: null,
          id: 111,
          images: null,
          inventory: null,
          is_active: null,
          is_available_to_book: null,
          is_bed_configuration_enabled: null,
          is_channel_enabled: null,
          main_image: null,
          name: 'Premium Suites',
          not_available_reason: null,
          occupancy_default: null,
          occupancy_max: null,
          physicalrooms: null,
          rate: null,
          rateplans: null,
          size: null,
          smoking_option: null,
        },
        sharing_persons: [
          {
            address: null,
            alternative_email: null,
            cci: null,
            city: null,
            country: {
              cities: null,
              code: null,
              currency: null,
              flag: null,
              gmt_offset: 0,
              id: null,
              market_places: null,
              name: null,
              phone_prefix: null,
            },
            country_id: null,
            country_phone_prefix: null,
            dob: '1900-01-01',
            email: null,
            first_name: 'test',
            id: 131083,
            id_info: {
              number: '',
              type: {
                code: '001',
                description: 'Passport',
              },
            },
            is_main: true,
            last_name: 'test',
            mobile: null,
            mobile_without_prefix: null,
            nbr_confirmed_bookings: 0,
            notes: null,
            password: null,
            subscribe_to_news_letter: null,
          },
        ],
        smoking_option: null,
        taxes: null,
        to_date: '2025-11-26',
        total: 126.0,
        unit: null,
      },
      {
        applicable_policies: [
          {
            brackets: [
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '000',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: 'Tuesday, 25 Nov 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: 'Do not use',
              },
            ],
            combined_statement: '',
            type: 'cancelation',
          },
          {
            brackets: [
              {
                amount: 31.5,
                amount_formatted: 'US$31.50',
                code: '001',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: null,
                gross_amount: 34.965,
                gross_amount_formatted: 'US$34.97',
                statement: '25% of your booking total will be charged',
              },
            ],
            combined_statement: '25% of your booking total will be charged',
            type: 'guarantee',
          },
        ],
        assigned_units_pool: null,
        bed_preference: null,
        calendar_extra: '',
        check_in: false,
        cost: null,
        days: [
          {
            amount: 126.0,
            cost: null,
            date: '2025-11-26',
          },
        ],
        departure_time: {
          code: '015',
          description: '11:00',
        },
        from_date: '2025-11-26',
        gross_cost: null,
        gross_guarantee: 34.965,
        gross_total: 139.86,
        guarantee: 31.5,
        guest: {
          address: null,
          alternative_email: null,
          cci: null,
          city: null,
          country: null,
          country_id: null,
          country_phone_prefix: null,
          dob: null,
          email: null,
          first_name: 'test',
          id: null,
          id_info: null,
          is_main: false,
          last_name: 'test',
          mobile: null,
          mobile_without_prefix: null,
          nbr_confirmed_bookings: 0,
          notes: null,
          password: null,
          subscribe_to_news_letter: null,
        },
        identifier: '8eb8f464-0be2-479f-959c-5fb45284191d',
        in_out: {
          code: '000',
          description: 'Not Set',
        },
        is_split: true,
        notes: '',
        occupancy: {
          adult_nbr: 2,
          children_nbr: 0,
          infant_nbr: null,
        },
        ota_meta: null,
        ota_meta_plain: null,
        ota_taxes: null,
        ota_unique_id: null,
        parent_room_identifier: 'ed68af2f-04e9-4e7b-9e54-ae9a2d059fb7',
        prepayment_amount: null,
        prepayment_amount_gross: null,
        rateplan: {
          agents: null,
          assignable_units: null,
          cancelation: '',
          custom_text: null,
          extra_bed_for_code: null,
          extra_bed_max: null,
          extra_bed_rate_per_night: null,
          extra_bed_rate_per_night_additional_child: null,
          extra_bed_rate_per_night_first_child: null,
          guarantee: '25% of your booking total will be charged',
          id: 123,
          is_active: null,
          is_available_to_book: false,
          is_booking_engine_enabled: null,
          is_channel_enabled: null,
          is_closed: null,
          is_derived: false,
          is_extra_bed_free_for_children: false,
          is_non_refundable: false,
          is_targeting_travel_agency: null,
          meal_plan: {
            code: '002',
            name: null,
          },
          name: 'Car Rental included/Bed-&-breakfast',
          not_available_reason: null,
          pre_payment_amount: null,
          pre_payment_amount_gross: null,
          rate_restrictions: null,
          selected_variation: {
            IS_MLS_VIOLATED: false,
            MLS_ALERT: null,
            MLS_ALERT_VALUE: null,
            adult_child_offering: '2 adults',
            adult_nbr: 2,
            amount: null,
            amount_gross: null,
            amount_per_night: null,
            amount_per_night_gross: null,
            applicable_policies: null,
            bed_preference_code: null,
            child_nbr: 0,
            discount_pct: null,
            discounted_amount: null,
            discounted_gross_amount: null,
            extra_bed_free_nbr: null,
            extra_bed_nbr: null,
            extra_bed_rate_per_night: null,
            food_nbr_upsell: 0,
            infant_nbr: null,
            is_lmd: null,
            nights: null,
            nights_nbr: null,
            prepayment_amount: null,
            prepayment_amount_gross: null,
            rate_plan_id: 123,
            smoking_code: null,
            total_before_discount: null,
          },
          sell_mode: null,
          short_name: 'Bed & breakfast',
          sleeps: null,
          variations: null,
        },
        roomtype: {
          amenities: null,
          availabilities: null,
          bedding_setup: null,
          description: null,
          exposed_inventory: null,
          id: 110,
          images: null,
          inventory: null,
          is_active: null,
          is_available_to_book: null,
          is_bed_configuration_enabled: null,
          is_channel_enabled: null,
          main_image: null,
          name: 'Standard Rooms',
          not_available_reason: null,
          occupancy_default: null,
          occupancy_max: null,
          physicalrooms: null,
          rate: null,
          rateplans: null,
          size: null,
          smoking_option: null,
        },
        sharing_persons: [
          {
            address: null,
            alternative_email: null,
            cci: null,
            city: null,
            country: {
              cities: null,
              code: null,
              currency: null,
              flag: null,
              gmt_offset: 0,
              id: null,
              market_places: null,
              name: null,
              phone_prefix: null,
            },
            country_id: null,
            country_phone_prefix: null,
            dob: '1900-01-01',
            email: null,
            first_name: 'test',
            id: 131085,
            id_info: {
              number: '',
              type: {
                code: '001',
                description: 'Passport',
              },
            },
            is_main: true,
            last_name: 'test',
            mobile: null,
            mobile_without_prefix: null,
            nbr_confirmed_bookings: 0,
            notes: null,
            password: null,
            subscribe_to_news_letter: null,
          },
        ],
        smoking_option: null,
        taxes: null,
        to_date: '2025-11-27',
        total: 126.0,
        unit: null,
      },
    ],
    source: {
      code: '003',
      description: 'Phone/Email',
      id: null,
      tag: '',
      type: null,
    },
    status: {
      code: '002',
      description: 'Confirmed',
    },
    system_id: 14952444,
    to_date: '2025-11-27',
    total: 252.0,
  },
  {
    agent: null,
    allowed_actions: [
      {
        code: '001',
        description: 'Pending',
      },
      {
        code: 'CANC_RA',
        description: 'Cancel',
      },
      {
        code: 'NOSHOW_RA',
        description: 'No show',
      },
    ],
    arrival: {
      code: '001',
      description: 'Not sure yet',
    },
    booked_on: {
      date: '2025-11-25',
      hour: 11,
      minute: 7,
    },
    booking_nbr: '80537381041',
    bypassed_ota_revisions: null,
    channel_booking_nbr: null,
    company_name: null,
    company_tax_nbr: null,
    cost: null,
    currency: {
      code: 'USD',
      id: 4,
      symbol: 'US$',
    },
    events: [
      {
        date: '2025-11-25',
        hour: 11,
        id: null,
        minute: 7,
        second: 28,
        type: 'Conf. email',
        user: 'System',
      },
      {
        date: '2025-11-25',
        hour: 11,
        id: 8787694,
        minute: 7,
        second: 21,
        type: 'Confirmed',
        user: 'A35',
      },
    ],
    extra_services: null,
    extras: [
      {
        key: 'is_backend',
        value: 'true',
      },
    ],
    financial: {
      cancelation_penality_as_if_today: 469.53,
      collected: 0.0,
      due_amount: 469.53,
      due_dates: null,
      gross_cost: 0.0,
      gross_total: 469.53,
      invoice_nbr: '805373',
      payments: null,
      refunds: 0.0,
      total_amount: 423.0,
    },
    format: {
      from_date: 'Tue, 25 Nov 2025',
      to_date: 'Sun, 30 Nov 2025',
    },
    from_date: '2025-11-25',
    guest: {
      address: '',
      alternative_email: null,
      cci: null,
      city: null,
      country: {
        cities: null,
        code: 'BZ',
        currency: null,
        flag: null,
        gmt_offset: 0,
        id: 486,
        market_places: null,
        name: 'Belize',
        phone_prefix: null,
      },
      country_id: 486,
      country_phone_prefix: '+501',
      dob: null,
      email: 'estest.test@gmail.com',
      first_name: 'Fa',
      id: 528363,
      id_info: null,
      is_main: false,
      last_name: 'aL',
      mobile: '12345678',
      mobile_without_prefix: '12345678',
      nbr_confirmed_bookings: 50,
      notes: '',
      password: null,
      subscribe_to_news_letter: false,
    },
    is_direct: true,
    is_editable: true,
    is_in_loyalty_mode: false,
    is_pms_enabled: true,
    is_requested_to_cancel: null,
    occupancy: {
      adult_nbr: 2,
      children_nbr: 0,
      infant_nbr: 0,
    },
    origin: {
      Icon: 'https://x.igloorooms.com/assets/images/png/direct.png',
      Label: 'Direct | website',
    },
    ota_commission: null,
    ota_guarante: null,
    ota_guarantee_plain: null,
    ota_manipulations: null,
    ota_notes: null,
    ota_services: null,
    ota_services_plain: null,
    payment_collect: null,
    payment_type: null,
    pickup_info: null,
    promo_key: '',
    property: {
      address: null,
      adult_child_constraints: null,
      affiliates: null,
      agents: null,
      allowed_booking_sources: null,
      allowed_cards: null,
      allowed_payment_methods: null,
      amenities: null,
      aname: null,
      area: null,
      baby_cot_offering: null,
      be_listing_mode: null,
      calendar_extra: null,
      calendar_legends: null,
      city: null,
      cleaning_frequency: null,
      company: null,
      contacts: null,
      country: null,
      currency: null,
      description: null,
      extra_info: null,
      id: 42,
      images: null,
      internet_offering: null,
      is_automatic_check_in_out: null,
      is_be_enabled: null,
      is_frontdesk_enabled: null,
      is_multi_property: null,
      is_pms_enabled: null,
      is_vacation_rental: null,
      location: null,
      max_nights: 0,
      mpo: null,
      name: 'igloorooms Demo Hotel',
      parking_offering: null,
      payment_methods: null,
      perma_link: null,
      pets_acceptance: null,
      phone: null,
      pickup_service: null,
      postal: null,
      privacy_policy: null,
      promotions: null,
      registered_name: null,
      roomtypes: null,
      social_media: null,
      sources: null,
      space_theme: null,
      tags: null,
      tax_nbr: null,
      tax_statement: null,
      taxation_strategy: null,
      taxes: null,
      time_constraints: null,
    },
    remark: '',
    rooms: [
      {
        applicable_policies: [
          {
            brackets: [
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '007',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: 'Tuesday, 25 Nov 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: '0%',
              },
            ],
            combined_statement: '',
            type: 'cancelation',
          },
          {
            brackets: [
              {
                amount: 20.25,
                amount_formatted: 'US$20.25',
                code: '001',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: null,
                gross_amount: 22.4775,
                gross_amount_formatted: 'US$22.48',
                statement: '25% of your booking total will be charged',
              },
            ],
            combined_statement: '25% of your booking total will be charged',
            type: 'guarantee',
          },
        ],
        assigned_units_pool: 'e92357f0-62ae-433a-9c95-4553744b7e79',
        bed_preference: null,
        calendar_extra: '',
        check_in: false,
        cost: null,
        days: [
          {
            amount: 81.0,
            cost: null,
            date: '2025-11-25',
          },
        ],
        departure_time: {
          code: '',
          description: '',
        },
        from_date: '2025-11-25',
        gross_cost: null,
        gross_guarantee: 22.4775,
        gross_total: 89.91,
        guarantee: 20.25,
        guest: {
          address: null,
          alternative_email: null,
          cci: null,
          city: null,
          country: null,
          country_id: null,
          country_phone_prefix: null,
          dob: null,
          email: null,
          first_name: 'test',
          id: null,
          id_info: null,
          is_main: false,
          last_name: 'test',
          mobile: null,
          mobile_without_prefix: null,
          nbr_confirmed_bookings: 0,
          notes: null,
          password: null,
          subscribe_to_news_letter: null,
        },
        identifier: 'eaec5d7b-ac8a-4c7e-9268-4bc7afb33279',
        in_out: {
          code: '001',
          description: 'Checked in',
        },
        is_split: null,
        notes: '',
        occupancy: {
          adult_nbr: 2,
          children_nbr: 0,
          infant_nbr: null,
        },
        ota_meta: null,
        ota_meta_plain: null,
        ota_taxes: null,
        ota_unique_id: null,
        parent_room_identifier: null,
        prepayment_amount: null,
        prepayment_amount_gross: null,
        rateplan: {
          agents: null,
          assignable_units: null,
          cancelation: '',
          custom_text: null,
          extra_bed_for_code: null,
          extra_bed_max: null,
          extra_bed_rate_per_night: null,
          extra_bed_rate_per_night_additional_child: null,
          extra_bed_rate_per_night_first_child: null,
          guarantee: '25% of your booking total will be charged',
          id: 123,
          is_active: null,
          is_available_to_book: false,
          is_booking_engine_enabled: null,
          is_channel_enabled: null,
          is_closed: null,
          is_derived: false,
          is_extra_bed_free_for_children: false,
          is_non_refundable: false,
          is_targeting_travel_agency: null,
          meal_plan: {
            code: '002',
            name: null,
          },
          name: 'Car Rental included/Bed-&-breakfast',
          not_available_reason: null,
          pre_payment_amount: null,
          pre_payment_amount_gross: null,
          rate_restrictions: null,
          selected_variation: {
            IS_MLS_VIOLATED: false,
            MLS_ALERT: null,
            MLS_ALERT_VALUE: null,
            adult_child_offering: '2 adults',
            adult_nbr: 2,
            amount: null,
            amount_gross: null,
            amount_per_night: null,
            amount_per_night_gross: null,
            applicable_policies: null,
            bed_preference_code: null,
            child_nbr: 0,
            discount_pct: null,
            discounted_amount: null,
            discounted_gross_amount: null,
            extra_bed_free_nbr: null,
            extra_bed_nbr: null,
            extra_bed_rate_per_night: null,
            food_nbr_upsell: 0,
            infant_nbr: null,
            is_lmd: null,
            nights: null,
            nights_nbr: null,
            prepayment_amount: null,
            prepayment_amount_gross: null,
            rate_plan_id: 123,
            smoking_code: null,
            total_before_discount: null,
          },
          sell_mode: null,
          short_name: 'Bed & breakfast',
          sleeps: null,
          variations: null,
        },
        roomtype: {
          amenities: null,
          availabilities: null,
          bedding_setup: null,
          description: null,
          exposed_inventory: null,
          id: 110,
          images: null,
          inventory: null,
          is_active: null,
          is_available_to_book: null,
          is_bed_configuration_enabled: null,
          is_channel_enabled: null,
          main_image: null,
          name: 'Standard Rooms',
          not_available_reason: null,
          occupancy_default: null,
          occupancy_max: null,
          physicalrooms: null,
          rate: null,
          rateplans: null,
          size: null,
          smoking_option: null,
        },
        sharing_persons: [
          {
            address: null,
            alternative_email: null,
            cci: null,
            city: null,
            country: {
              cities: null,
              code: null,
              currency: null,
              flag: null,
              gmt_offset: 0,
              id: null,
              market_places: null,
              name: null,
              phone_prefix: null,
            },
            country_id: null,
            country_phone_prefix: null,
            dob: '1900-01-01',
            email: null,
            first_name: 'test',
            id: 130854,
            id_info: {
              number: '',
              type: {
                code: '001',
                description: 'Passport',
              },
            },
            is_main: true,
            last_name: 'test',
            mobile: null,
            mobile_without_prefix: null,
            nbr_confirmed_bookings: 0,
            notes: null,
            password: null,
            subscribe_to_news_letter: null,
          },
        ],
        smoking_option: null,
        taxes: null,
        to_date: '2025-11-26',
        total: 81.0,
        unit: {
          calendar_cell: null,
          hk_status: null,
          housekeeper: null,
          id: 16,
          is_active: null,
          name: '05',
        },
      },
      {
        applicable_policies: [
          {
            brackets: [
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '000',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: 'Tuesday, 25 Nov 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: 'Do not use',
              },
            ],
            combined_statement: '',
            type: 'cancelation',
          },
          {
            brackets: [
              {
                amount: 20.25,
                amount_formatted: 'US$20.25',
                code: '001',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: null,
                gross_amount: 22.4775,
                gross_amount_formatted: 'US$22.48',
                statement: '25% of your booking total will be charged',
              },
            ],
            combined_statement: '25% of your booking total will be charged',
            type: 'guarantee',
          },
        ],
        assigned_units_pool: '907e6d37-6c0c-492e-a72e-82d1d871db20',
        bed_preference: null,
        calendar_extra: '',
        check_in: false,
        cost: null,
        days: [
          {
            amount: 81.0,
            cost: null,
            date: '2025-11-26',
          },
        ],
        departure_time: {
          code: '',
          description: '',
        },
        from_date: '2025-11-26',
        gross_cost: null,
        gross_guarantee: 22.4775,
        gross_total: 89.91,
        guarantee: 20.25,
        guest: {
          address: null,
          alternative_email: null,
          cci: null,
          city: null,
          country: null,
          country_id: null,
          country_phone_prefix: null,
          dob: null,
          email: null,
          first_name: 'test',
          id: null,
          id_info: null,
          is_main: false,
          last_name: 'test',
          mobile: null,
          mobile_without_prefix: null,
          nbr_confirmed_bookings: 0,
          notes: null,
          password: null,
          subscribe_to_news_letter: null,
        },
        identifier: 'aae85c09-b8e8-4947-a212-d00393d16002',
        in_out: {
          code: '001',
          description: 'Checked in',
        },
        is_split: true,
        notes: '',
        occupancy: {
          adult_nbr: 2,
          children_nbr: 0,
          infant_nbr: null,
        },
        ota_meta: null,
        ota_meta_plain: null,
        ota_taxes: null,
        ota_unique_id: null,
        parent_room_identifier: 'eaec5d7b-ac8a-4c7e-9268-4bc7afb33279',
        prepayment_amount: null,
        prepayment_amount_gross: null,
        rateplan: {
          agents: null,
          assignable_units: null,
          cancelation: '',
          custom_text: null,
          extra_bed_for_code: null,
          extra_bed_max: null,
          extra_bed_rate_per_night: null,
          extra_bed_rate_per_night_additional_child: null,
          extra_bed_rate_per_night_first_child: null,
          guarantee: '25% of your booking total will be charged',
          id: 123,
          is_active: null,
          is_available_to_book: false,
          is_booking_engine_enabled: null,
          is_channel_enabled: null,
          is_closed: null,
          is_derived: false,
          is_extra_bed_free_for_children: false,
          is_non_refundable: false,
          is_targeting_travel_agency: null,
          meal_plan: {
            code: '002',
            name: null,
          },
          name: 'Car Rental included/Bed-&-breakfast',
          not_available_reason: null,
          pre_payment_amount: null,
          pre_payment_amount_gross: null,
          rate_restrictions: null,
          selected_variation: {
            IS_MLS_VIOLATED: false,
            MLS_ALERT: null,
            MLS_ALERT_VALUE: null,
            adult_child_offering: '2 adults',
            adult_nbr: 2,
            amount: null,
            amount_gross: null,
            amount_per_night: null,
            amount_per_night_gross: null,
            applicable_policies: null,
            bed_preference_code: null,
            child_nbr: 0,
            discount_pct: null,
            discounted_amount: null,
            discounted_gross_amount: null,
            extra_bed_free_nbr: null,
            extra_bed_nbr: null,
            extra_bed_rate_per_night: null,
            food_nbr_upsell: 0,
            infant_nbr: null,
            is_lmd: null,
            nights: null,
            nights_nbr: null,
            prepayment_amount: null,
            prepayment_amount_gross: null,
            rate_plan_id: 123,
            smoking_code: null,
            total_before_discount: null,
          },
          sell_mode: null,
          short_name: 'Bed & breakfast',
          sleeps: null,
          variations: null,
        },
        roomtype: {
          amenities: null,
          availabilities: null,
          bedding_setup: null,
          description: null,
          exposed_inventory: null,
          id: 110,
          images: null,
          inventory: null,
          is_active: null,
          is_available_to_book: null,
          is_bed_configuration_enabled: null,
          is_channel_enabled: null,
          main_image: null,
          name: 'Standard Rooms',
          not_available_reason: null,
          occupancy_default: null,
          occupancy_max: null,
          physicalrooms: null,
          rate: null,
          rateplans: null,
          size: null,
          smoking_option: null,
        },
        sharing_persons: [
          {
            address: null,
            alternative_email: null,
            cci: null,
            city: null,
            country: {
              cities: null,
              code: null,
              currency: null,
              flag: null,
              gmt_offset: 0,
              id: null,
              market_places: null,
              name: null,
              phone_prefix: null,
            },
            country_id: null,
            country_phone_prefix: null,
            dob: '1900-01-01',
            email: null,
            first_name: 'test',
            id: 130855,
            id_info: {
              number: '',
              type: {
                code: '001',
                description: 'Passport',
              },
            },
            is_main: true,
            last_name: 'test',
            mobile: null,
            mobile_without_prefix: null,
            nbr_confirmed_bookings: 0,
            notes: null,
            password: null,
            subscribe_to_news_letter: null,
          },
        ],
        smoking_option: null,
        taxes: null,
        to_date: '2025-11-27',
        total: 81.0,
        unit: {
          calendar_cell: null,
          hk_status: null,
          housekeeper: null,
          id: 17,
          is_active: null,
          name: '06',
        },
      },
      {
        applicable_policies: [
          {
            brackets: [
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '000',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: 'Tuesday, 25 Nov 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: 'Do not use',
              },
            ],
            combined_statement: '',
            type: 'cancelation',
          },
          {
            brackets: [
              {
                amount: 20.25,
                amount_formatted: 'US$20.25',
                code: '001',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: null,
                gross_amount: 22.4775,
                gross_amount_formatted: 'US$22.48',
                statement: '25% of your booking total will be charged',
              },
            ],
            combined_statement: '25% of your booking total will be charged',
            type: 'guarantee',
          },
        ],
        assigned_units_pool: '06616072-7947-4409-b524-e4509e7f6552',
        bed_preference: null,
        calendar_extra: '',
        check_in: false,
        cost: null,
        days: [
          {
            amount: 81.0,
            cost: null,
            date: '2025-11-27',
          },
        ],
        departure_time: {
          code: '',
          description: '',
        },
        from_date: '2025-11-27',
        gross_cost: null,
        gross_guarantee: 22.4775,
        gross_total: 89.91,
        guarantee: 20.25,
        guest: {
          address: null,
          alternative_email: null,
          cci: null,
          city: null,
          country: null,
          country_id: null,
          country_phone_prefix: null,
          dob: null,
          email: null,
          first_name: 'test',
          id: null,
          id_info: null,
          is_main: false,
          last_name: 'test',
          mobile: null,
          mobile_without_prefix: null,
          nbr_confirmed_bookings: 0,
          notes: null,
          password: null,
          subscribe_to_news_letter: null,
        },
        identifier: '1b453b0c-3824-44c9-a1f2-f4e90147458c',
        in_out: {
          code: '001',
          description: 'Checked in',
        },
        is_split: true,
        notes: '',
        occupancy: {
          adult_nbr: 2,
          children_nbr: 0,
          infant_nbr: null,
        },
        ota_meta: null,
        ota_meta_plain: null,
        ota_taxes: null,
        ota_unique_id: null,
        parent_room_identifier: 'aae85c09-b8e8-4947-a212-d00393d16002',
        prepayment_amount: null,
        prepayment_amount_gross: null,
        rateplan: {
          agents: null,
          assignable_units: null,
          cancelation: '',
          custom_text: null,
          extra_bed_for_code: null,
          extra_bed_max: null,
          extra_bed_rate_per_night: null,
          extra_bed_rate_per_night_additional_child: null,
          extra_bed_rate_per_night_first_child: null,
          guarantee: '25% of your booking total will be charged',
          id: 123,
          is_active: null,
          is_available_to_book: false,
          is_booking_engine_enabled: null,
          is_channel_enabled: null,
          is_closed: null,
          is_derived: false,
          is_extra_bed_free_for_children: false,
          is_non_refundable: false,
          is_targeting_travel_agency: null,
          meal_plan: {
            code: '002',
            name: null,
          },
          name: 'Car Rental included/Bed-&-breakfast',
          not_available_reason: null,
          pre_payment_amount: null,
          pre_payment_amount_gross: null,
          rate_restrictions: null,
          selected_variation: {
            IS_MLS_VIOLATED: false,
            MLS_ALERT: null,
            MLS_ALERT_VALUE: null,
            adult_child_offering: '2 adults',
            adult_nbr: 2,
            amount: null,
            amount_gross: null,
            amount_per_night: null,
            amount_per_night_gross: null,
            applicable_policies: null,
            bed_preference_code: null,
            child_nbr: 0,
            discount_pct: null,
            discounted_amount: null,
            discounted_gross_amount: null,
            extra_bed_free_nbr: null,
            extra_bed_nbr: null,
            extra_bed_rate_per_night: null,
            food_nbr_upsell: 0,
            infant_nbr: null,
            is_lmd: null,
            nights: null,
            nights_nbr: null,
            prepayment_amount: null,
            prepayment_amount_gross: null,
            rate_plan_id: 123,
            smoking_code: null,
            total_before_discount: null,
          },
          sell_mode: null,
          short_name: 'Bed & breakfast',
          sleeps: null,
          variations: null,
        },
        roomtype: {
          amenities: null,
          availabilities: null,
          bedding_setup: null,
          description: null,
          exposed_inventory: null,
          id: 110,
          images: null,
          inventory: null,
          is_active: null,
          is_available_to_book: null,
          is_bed_configuration_enabled: null,
          is_channel_enabled: null,
          main_image: null,
          name: 'Standard Rooms',
          not_available_reason: null,
          occupancy_default: null,
          occupancy_max: null,
          physicalrooms: null,
          rate: null,
          rateplans: null,
          size: null,
          smoking_option: null,
        },
        sharing_persons: [
          {
            address: null,
            alternative_email: null,
            cci: null,
            city: null,
            country: {
              cities: null,
              code: null,
              currency: null,
              flag: null,
              gmt_offset: 0,
              id: null,
              market_places: null,
              name: null,
              phone_prefix: null,
            },
            country_id: null,
            country_phone_prefix: null,
            dob: '1900-01-01',
            email: null,
            first_name: 'test',
            id: 130856,
            id_info: {
              number: '',
              type: {
                code: '001',
                description: 'Passport',
              },
            },
            is_main: true,
            last_name: 'test',
            mobile: null,
            mobile_without_prefix: null,
            nbr_confirmed_bookings: 0,
            notes: null,
            password: null,
            subscribe_to_news_letter: null,
          },
        ],
        smoking_option: null,
        taxes: null,
        to_date: '2025-11-28',
        total: 81.0,
        unit: {
          calendar_cell: null,
          hk_status: null,
          housekeeper: null,
          id: 26,
          is_active: null,
          name: '07',
        },
      },
      {
        applicable_policies: [
          {
            brackets: [
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '000',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: 'Tuesday, 25 Nov 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: 'Do not use',
              },
            ],
            combined_statement: '',
            type: 'cancelation',
          },
          {
            brackets: [
              {
                amount: 22.5,
                amount_formatted: 'US$22.50',
                code: '001',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: null,
                gross_amount: 24.975,
                gross_amount_formatted: 'US$24.98',
                statement: '25% of your booking total will be charged',
              },
            ],
            combined_statement: '25% of your booking total will be charged',
            type: 'guarantee',
          },
        ],
        assigned_units_pool: '8aa33ef5-a670-457d-9f6e-b94f1d1ff7ce',
        bed_preference: null,
        calendar_extra: '',
        check_in: false,
        cost: null,
        days: [
          {
            amount: 90.0,
            cost: null,
            date: '2025-11-28',
          },
        ],
        departure_time: {
          code: '',
          description: '',
        },
        from_date: '2025-11-28',
        gross_cost: null,
        gross_guarantee: 24.975,
        gross_total: 99.9,
        guarantee: 22.5,
        guest: {
          address: null,
          alternative_email: null,
          cci: null,
          city: null,
          country: null,
          country_id: null,
          country_phone_prefix: null,
          dob: null,
          email: null,
          first_name: 'test',
          id: null,
          id_info: null,
          is_main: false,
          last_name: 'test',
          mobile: null,
          mobile_without_prefix: null,
          nbr_confirmed_bookings: 0,
          notes: null,
          password: null,
          subscribe_to_news_letter: null,
        },
        identifier: '5dd224df-5f2b-4800-a256-f8e83e8389fe',
        in_out: {
          code: '001',
          description: 'Checked in',
        },
        is_split: true,
        notes: '',
        occupancy: {
          adult_nbr: 2,
          children_nbr: 0,
          infant_nbr: null,
        },
        ota_meta: null,
        ota_meta_plain: null,
        ota_taxes: null,
        ota_unique_id: null,
        parent_room_identifier: '1b453b0c-3824-44c9-a1f2-f4e90147458c',
        prepayment_amount: null,
        prepayment_amount_gross: null,
        rateplan: {
          agents: null,
          assignable_units: null,
          cancelation: '',
          custom_text: null,
          extra_bed_for_code: null,
          extra_bed_max: null,
          extra_bed_rate_per_night: null,
          extra_bed_rate_per_night_additional_child: null,
          extra_bed_rate_per_night_first_child: null,
          guarantee: '25% of your booking total will be charged',
          id: 123,
          is_active: null,
          is_available_to_book: false,
          is_booking_engine_enabled: null,
          is_channel_enabled: null,
          is_closed: null,
          is_derived: false,
          is_extra_bed_free_for_children: false,
          is_non_refundable: false,
          is_targeting_travel_agency: null,
          meal_plan: {
            code: '002',
            name: null,
          },
          name: 'Car Rental included/Bed-&-breakfast',
          not_available_reason: null,
          pre_payment_amount: null,
          pre_payment_amount_gross: null,
          rate_restrictions: null,
          selected_variation: {
            IS_MLS_VIOLATED: false,
            MLS_ALERT: null,
            MLS_ALERT_VALUE: null,
            adult_child_offering: '2 adults',
            adult_nbr: 2,
            amount: null,
            amount_gross: null,
            amount_per_night: null,
            amount_per_night_gross: null,
            applicable_policies: null,
            bed_preference_code: null,
            child_nbr: 0,
            discount_pct: null,
            discounted_amount: null,
            discounted_gross_amount: null,
            extra_bed_free_nbr: null,
            extra_bed_nbr: null,
            extra_bed_rate_per_night: null,
            food_nbr_upsell: 0,
            infant_nbr: null,
            is_lmd: null,
            nights: null,
            nights_nbr: null,
            prepayment_amount: null,
            prepayment_amount_gross: null,
            rate_plan_id: 123,
            smoking_code: null,
            total_before_discount: null,
          },
          sell_mode: null,
          short_name: 'Bed & breakfast',
          sleeps: null,
          variations: null,
        },
        roomtype: {
          amenities: null,
          availabilities: null,
          bedding_setup: null,
          description: null,
          exposed_inventory: null,
          id: 110,
          images: null,
          inventory: null,
          is_active: null,
          is_available_to_book: null,
          is_bed_configuration_enabled: null,
          is_channel_enabled: null,
          main_image: null,
          name: 'Standard Rooms',
          not_available_reason: null,
          occupancy_default: null,
          occupancy_max: null,
          physicalrooms: null,
          rate: null,
          rateplans: null,
          size: null,
          smoking_option: null,
        },
        sharing_persons: [
          {
            address: null,
            alternative_email: null,
            cci: null,
            city: null,
            country: {
              cities: null,
              code: null,
              currency: null,
              flag: null,
              gmt_offset: 0,
              id: null,
              market_places: null,
              name: null,
              phone_prefix: null,
            },
            country_id: null,
            country_phone_prefix: null,
            dob: '1900-01-01',
            email: null,
            first_name: 'test',
            id: 131081,
            id_info: {
              number: '',
              type: {
                code: '001',
                description: 'Passport',
              },
            },
            is_main: true,
            last_name: 'test',
            mobile: null,
            mobile_without_prefix: null,
            nbr_confirmed_bookings: 0,
            notes: null,
            password: null,
            subscribe_to_news_letter: null,
          },
        ],
        smoking_option: null,
        taxes: null,
        to_date: '2025-11-29',
        total: 90.0,
        unit: {
          calendar_cell: null,
          hk_status: null,
          housekeeper: null,
          id: 17,
          is_active: null,
          name: '06',
        },
      },
      {
        applicable_policies: [
          {
            brackets: [
              {
                amount: 0.0,
                amount_formatted: 'US$0.00',
                code: '000',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: 'Tuesday, 25 Nov 2025, 14:00',
                gross_amount: 0.0,
                gross_amount_formatted: 'US$0.00',
                statement: 'Do not use',
              },
            ],
            combined_statement: '',
            type: 'cancelation',
          },
          {
            brackets: [
              {
                amount: 22.5,
                amount_formatted: 'US$22.50',
                code: '001',
                currency_id: 4,
                due_on: '2025-11-25',
                due_on_formatted: null,
                gross_amount: 24.975,
                gross_amount_formatted: 'US$24.98',
                statement: '25% of your booking total will be charged',
              },
            ],
            combined_statement: '25% of your booking total will be charged',
            type: 'guarantee',
          },
        ],
        assigned_units_pool: 'c0239d40-74f7-4ca7-aca9-5024615509ec',
        bed_preference: null,
        calendar_extra: '',
        check_in: false,
        cost: null,
        days: [
          {
            amount: 90.0,
            cost: null,
            date: '2025-11-29',
          },
        ],
        departure_time: {
          code: '029',
          description: '18:00',
        },
        from_date: '2025-11-29',
        gross_cost: null,
        gross_guarantee: 24.975,
        gross_total: 99.9,
        guarantee: 22.5,
        guest: {
          address: null,
          alternative_email: null,
          cci: null,
          city: null,
          country: null,
          country_id: null,
          country_phone_prefix: null,
          dob: null,
          email: null,
          first_name: 'test',
          id: null,
          id_info: null,
          is_main: false,
          last_name: 'test',
          mobile: null,
          mobile_without_prefix: null,
          nbr_confirmed_bookings: 0,
          notes: null,
          password: null,
          subscribe_to_news_letter: null,
        },
        identifier: '6bf0f61d-9a44-4e0c-bbe0-cdf6687750ab',
        in_out: {
          code: '001',
          description: 'Checked in',
        },
        is_split: true,
        notes: '',
        occupancy: {
          adult_nbr: 2,
          children_nbr: 0,
          infant_nbr: null,
        },
        ota_meta: null,
        ota_meta_plain: null,
        ota_taxes: null,
        ota_unique_id: null,
        parent_room_identifier: '5dd224df-5f2b-4800-a256-f8e83e8389fe',
        prepayment_amount: null,
        prepayment_amount_gross: null,
        rateplan: {
          agents: null,
          assignable_units: null,
          cancelation: '',
          custom_text: null,
          extra_bed_for_code: null,
          extra_bed_max: null,
          extra_bed_rate_per_night: null,
          extra_bed_rate_per_night_additional_child: null,
          extra_bed_rate_per_night_first_child: null,
          guarantee: '25% of your booking total will be charged',
          id: 123,
          is_active: null,
          is_available_to_book: false,
          is_booking_engine_enabled: null,
          is_channel_enabled: null,
          is_closed: null,
          is_derived: false,
          is_extra_bed_free_for_children: false,
          is_non_refundable: false,
          is_targeting_travel_agency: null,
          meal_plan: {
            code: '002',
            name: null,
          },
          name: 'Car Rental included/Bed-&-breakfast',
          not_available_reason: null,
          pre_payment_amount: null,
          pre_payment_amount_gross: null,
          rate_restrictions: null,
          selected_variation: {
            IS_MLS_VIOLATED: false,
            MLS_ALERT: null,
            MLS_ALERT_VALUE: null,
            adult_child_offering: '2 adults',
            adult_nbr: 2,
            amount: null,
            amount_gross: null,
            amount_per_night: null,
            amount_per_night_gross: null,
            applicable_policies: null,
            bed_preference_code: null,
            child_nbr: 0,
            discount_pct: null,
            discounted_amount: null,
            discounted_gross_amount: null,
            extra_bed_free_nbr: null,
            extra_bed_nbr: null,
            extra_bed_rate_per_night: null,
            food_nbr_upsell: 0,
            infant_nbr: null,
            is_lmd: null,
            nights: null,
            nights_nbr: null,
            prepayment_amount: null,
            prepayment_amount_gross: null,
            rate_plan_id: 123,
            smoking_code: null,
            total_before_discount: null,
          },
          sell_mode: null,
          short_name: 'Bed & breakfast',
          sleeps: null,
          variations: null,
        },
        roomtype: {
          amenities: null,
          availabilities: null,
          bedding_setup: null,
          description: null,
          exposed_inventory: null,
          id: 110,
          images: null,
          inventory: null,
          is_active: null,
          is_available_to_book: null,
          is_bed_configuration_enabled: null,
          is_channel_enabled: null,
          main_image: null,
          name: 'Standard Rooms',
          not_available_reason: null,
          occupancy_default: null,
          occupancy_max: null,
          physicalrooms: null,
          rate: null,
          rateplans: null,
          size: null,
          smoking_option: null,
        },
        sharing_persons: [
          {
            address: null,
            alternative_email: null,
            cci: null,
            city: null,
            country: {
              cities: null,
              code: null,
              currency: null,
              flag: null,
              gmt_offset: 0,
              id: null,
              market_places: null,
              name: null,
              phone_prefix: null,
            },
            country_id: null,
            country_phone_prefix: null,
            dob: '1900-01-01',
            email: null,
            first_name: 'test',
            id: 131082,
            id_info: {
              number: '',
              type: {
                code: '001',
                description: 'Passport',
              },
            },
            is_main: true,
            last_name: 'test',
            mobile: null,
            mobile_without_prefix: null,
            nbr_confirmed_bookings: 0,
            notes: null,
            password: null,
            subscribe_to_news_letter: null,
          },
        ],
        smoking_option: null,
        taxes: null,
        to_date: '2025-11-30',
        total: 90.0,
        unit: {
          calendar_cell: null,
          hk_status: null,
          housekeeper: null,
          id: 26,
          is_active: null,
          name: '07',
        },
      },
    ],
    source: {
      code: null,
      description: null,
      id: null,
      tag: '',
      type: null,
    },
    status: {
      code: '002',
      description: 'Confirmed',
    },
    system_id: 14952310,
    to_date: '2025-11-30',
    total: 423.0,
  },
];
