# .github/workflows/deploy.yml
name: Build and deploy dist

on:
  push:
    branches:
      - guest-management

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          # replace with your target repo’s full name
          repository: David1Chowaifaty/igloo-calendar-main-web
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: target-repo
      - name: Replace dist folder
        run: |
          rm -rf target-repo/dist
          cp -R dist target-repo/dist

      - name: Commit & push to target repo
        run: |
          cd  target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "Auto-update dist from ${{ github.repository }}@${{ github.sha }}"
          git push

      - name: Done
        run: echo "✅ dist has been pushed to your target repo"
