# # # .github/workflows/deploy.yml
# # # name: Build and deploy dist

# # # on:
# # #   push:
# # #     branches:
# # #       - guest-management

# # # jobs:
# # #   build-and-deploy:
# # #     runs-on: ubuntu-latest
# # #     steps:
# # #       - uses: actions/checkout@v4
# # #       - uses: actions/setup-node@v4
# # #         with:
# # #           node-version: 20
# # #           cache: 'npm'
# # #       - name: Install dependencies
# # #         run: npm ci

# # #       - name: Build project
# # #         run: npm run build

# # #       - name: Checkout target repo
# # #         uses: actions/checkout@v3
# # #         with:
# # #           # replace with your target repo's full name
# # #           repository: David1Chowaifaty/igloo-calendar-main-web
# # #           token: ${{ secrets.TARGET_REPO_TOKEN }}
# # #           path: target-repo
# # #       - name: Replace dist folder
# # #         run: |
# # #           rm -rf target-repo/dist
# # #           cp -R dist target-repo/dist

# # #       - name: Commit & push to target repo
# # #         run: |
# # #           cd  target-repo
# # #           git config user.name "github-actions[bot]"
# # #           git config user.email "github-actions[bot]@users.noreply.github.com"
# # #           git add dist
# # #           git commit -m "Auto-update dist from ${{ github.repository }}@${{ github.sha }}"
# # #           git push

# # #       - name: Done
# # #         run: echo "✅ dist has been pushed to your target repo"
# # # .github/workflows/deploy.yml
# # name: Build and deploy dist

# # on:
# #   push:
# #     branches:
# #       - guest-management

# # jobs:
# #   build-and-deploy:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - uses: actions/checkout@v4

# #       - uses: actions/setup-node@v4
# #         with:
# #           node-version: 20
# #           cache: 'npm'

# #       # Add node_modules caching for faster installs
# #       - name: Cache node_modules
# #         uses: actions/cache@v4
# #         with:
# #           path: node_modules
# #           key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
# #           restore-keys: |
# #             ${{ runner.os }}-node-modules-

# #       - name: Install dependencies
# #         run: |
# #           if [ ! -d "node_modules" ]; then
# #             npm ci
# #           else
# #             echo "node_modules cache hit, skipping npm ci"
# #           fi

# #       - name: Build project
# #         run: npm run build

# #       - name: Checkout target repo
# #         uses: actions/checkout@v4 # Updated to v4
# #         with:
# #           repository: David1Chowaifaty/igloo-calendar-main-web
# #           token: ${{ secrets.TARGET_REPO_TOKEN }}
# #           path: target-repo

# #       - name: Replace dist folder
# #         run: |
# #           rm -rf target-repo/dist
# #           cp -R dist target-repo/dist

# #       - name: Commit & push to target repo
# #         run: |
# #           cd target-repo
# #           git config user.name "github-actions[bot]"
# #           git config user.email "github-actions[bot]@users.noreply.github.com"
# #           git add dist
# #           git commit -m "Auto-update dist from ${{ github.repository }}@${{ github.sha }}"
# #           git push

# #       - name: Done
# #         run: echo "✅ dist has been pushed to your target repo"
name: Build and deploy dist

on:
  push:
    branches:
      - guest-management
      - bulk-front

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # optional: caches npm's internal cache for speed

      - name: Install dependencies
        run: npm ci # always install fresh modules

      - name: Clean previous build
        run: rm -rf dist # ensure no leftover artifacts

      - name: Build project
        run: npm run build # produces a fresh dist/

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: David1Chowaifaty/igloo-calendar-main-web
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: target-repo

      - name: Replace dist folder
        run: |
          rm -rf target-repo/dist
          cp -R dist target-repo/dist

      - name: Commit & push to target repo
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          # only commit if there are changes
          git diff --cached --quiet || git commit -m "Auto-update dist from ${{ github.repository }}@${{ github.sha }}"
          git push

      - name: Done
        run: echo "✅ dist has been pushed to the target repo"
